import type { Provider } from "../providers"
import type { HealthResult } from "../health"
import { homedir } from "os"

export interface AntigravityProvider {
  name: string
  base_url: string
  env_key?: string
  model?: string
}

export function generateAntigravityConfig(
  providers: Array<{ provider: Provider; health: HealthResult }>,
): string {
  const lines: string[] = []
  lines.push("# Generated by multi-provider-setup")
  lines.push("")

  for (const { provider, health } of providers) {
    if (health.status !== "ok") continue

    const id = provider.id

    lines.push(`# ${provider.name}`)
    lines.push(`# base_url = "${provider.baseURL}"`)
    const envKey = provider.envKey || `${provider.id.toUpperCase().replace(/[^A-Z0-9_]/g, "_")}_API_KEY`
    lines.push(`# env_key = "${envKey}"`)

    if (health.models && health.models.length > 0) {
      lines.push(`# model = "${health.models[0]}"`)
    }
    lines.push("")
  }

  return lines.join("\n")
}

export function getAntigravityConfigPath(): string {
  return homedir() + "/.config/antigravity/config.toml"
}
