import type { Provider } from "../providers"
import type { HealthResult } from "../health"
import { homedir } from "os"

export interface CodexProvider {
  name: string
  base_url: string
  env_key?: string
  wire_api: "responses" | "chat" | "chat-completions"
  requires_openai_auth?: boolean
  http_headers?: Record<string, string>
  query_params?: Record<string, string>
  stream_idle_timeout_ms?: number
}

export type CodexConfig = Record<string, CodexProvider>

const RESERVED_IDS = new Set(["openai", "ollama", "lmstudio"])

function toTomlValue(val: unknown, indent = 0): string {
  const pad = " ".repeat(indent)
  if (typeof val === "string") return `${pad}"${val.replace(/"/g, '\\"')}"`
  if (typeof val === "number") return `${pad}${val}`
  if (typeof val === "boolean") return `${pad}${val ? "true" : "false"}`
  if (val === null || val === undefined) return ""
  if (Array.isArray(val)) {
    if (val.length === 0) return `${pad}[]`
    return `${pad}[\n${val.map(v => `${pad}  "${v}"`).join(",\n")}\n${pad}]`
  }
  if (typeof val === "object") {
    const entries = Object.entries(val as Record<string, unknown>)
    if (entries.length === 0) return `${pad}{}`
    return `\n${entries.map(([k, v]) => `${pad}${k} = ${toTomlValue(v, indent)}`).join("\n")}`
  }
  return `${pad}"${String(val)}"`
}

export function generateCodexConfig(
  providers: Array<{ provider: Provider; health: HealthResult }>,
): string {
  const lines: string[] = []
  lines.push("# Generated by multi-provider-setup")
  lines.push("# https://github.com/multi-provider-setup")
  lines.push("")

  for (const { provider, health } of providers) {
    if (health.status !== "ok") continue

    const id = RESERVED_IDS.has(provider.id) ? `${provider.id}-custom` : provider.id

    lines.push(`[model_providers.${id}]`)
    lines.push(`name = "${provider.name.replace(/"/g, '\\"')}"`)
    lines.push(`base_url = "${provider.baseURL}"`)

    const envKey = provider.envKey || `${provider.id.toUpperCase().replace(/[^A-Z0-9_]/g, "_")}_API_KEY`
    if (envKey) {
      lines.push(`env_key = "${envKey}"`)
    }

    lines.push(`wire_api = "chat"`)

    if (provider.id !== "openai") {
      lines.push(`requires_openai_auth = false`)
    }

    if (provider.id === "ollama" || provider.id === "lm-studio" || provider.id === "llamacpp") {
      lines.push(`stream_idle_timeout_ms = 120000`)
    }

    if (health.models && health.models.length > 0) {
      lines.push(`# Available models:`)
      for (const model of health.models.slice(0, 10)) {
        lines.push(`#   - ${model}`)
      }
      if (health.models.length > 10) {
        lines.push(`#   ... and ${health.models.length - 10} more`)
      }
    }

    lines.push("")
  }

  return lines.join("\n")
}

export function getCodexConfigPath(): string {
  return homedir() + "/.codex/config.toml"
}
