export interface Provider {
  id: string
  name: string
  baseURL: string
  envKey?: string
  website: string
  apiType: "openai" | "anthropic" | "openai-compatible"
  models?: string[]
  description?: string
  freeTier?: string
  noCc?: boolean
  permanentFree?: boolean
  recommended?: boolean
  tags?: string[]
}

const PROVIDERS: Provider[] = [
  {
    id: "groq",
    name: "Groq",
    baseURL: "https://api.groq.com/openai/v1",
    envKey: "GROQ_API_KEY",
    website: "https://console.groq.com",
    apiType: "openai-compatible",
    freeTier: "30 RPM, 1000-14400 RPD, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "cerebras",
    name: "Cerebras",
    baseURL: "https://api.cerebras.ai/v1",
    envKey: "CEREBRAS_API_KEY",
    website: "https://cloud.cerebras.ai",
    apiType: "openai-compatible",
    freeTier: "30 RPM, 1M tok/day, no CC, 2600 tok/s",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "google-gemini",
    name: "Google Gemini",
    baseURL: "https://generativelanguage.googleapis.com/v1beta",
    envKey: "GOOGLE_API_KEY",
    website: "https://aistudio.google.com",
    apiType: "openai-compatible",
    freeTier: "15-30 RPM, 50-1500 RPD, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "github-models",
    name: "GitHub Models",
    baseURL: "https://models.github.ai/inference",
    envKey: "GITHUB_TOKEN",
    website: "https://github.com/marketplace/models",
    apiType: "openai-compatible",
    freeTier: "10-15 RPM, 50-150 RPD, needs GitHub account",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "mistral",
    name: "Mistral AI (La Plateforme)",
    baseURL: "https://api.mistral.ai/v1",
    envKey: "MISTRAL_API_KEY",
    website: "https://console.mistral.ai",
    apiType: "openai-compatible",
    freeTier: "~1 RPS, ~500K TPM, 1B tok/month, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "cloudflare-workers-ai",
    name: "Cloudflare Workers AI",
    baseURL: "https://api.cloudflare.com/client/v4/accounts/{account}/ai/v1",
    envKey: "CLOUDFLARE_API_TOKEN",
    website: "https://dash.cloudflare.com",
    apiType: "openai-compatible",
    freeTier: "10K neurons/day, 300 RPM, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face Inference",
    baseURL: "https://router.huggingface.co/v1",
    envKey: "HF_TOKEN",
    website: "https://huggingface.co/settings/tokens",
    apiType: "openai-compatible",
    freeTier: "100K credits/month, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "zhipu",
    name: "Zhipu AI / GLM (智谱)",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    envKey: "ZHIPU_API_KEY",
    website: "https://open.bigmodel.cn",
    apiType: "openai-compatible",
    freeTier: "Free Flash models, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "ovhcloud",
    name: "OVHcloud AI Endpoints",
    baseURL: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    envKey: "OVH_AI_ENDPOINTS_ACCESS_TOKEN",
    website: "https://www.ovhcloud.com/en/public-cloud/ai-endpoints",
    apiType: "openai-compatible",
    freeTier: "2 RPM/IP anonymous, 400 RPM with key, $200 trial",
    noCc: true,
    permanentFree: true,
    description: "Hosted in EU, GDPR-compliant",
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM",
    baseURL: "https://integrate.api.nvidia.com/v1",
    envKey: "NVIDIA_API_KEY",
    website: "https://build.nvidia.com",
    apiType: "openai-compatible",
    freeTier: "~40 RPM, no daily cap, phone verification",
    permanentFree: true,
    description: "75+ free models",
  },
  {
    id: "codestral",
    name: "Codestral (Mistral Code)",
    baseURL: "https://api.mistral.ai/v1",
    envKey: "MISTRAL_API_KEY",
    website: "https://console.mistral.ai",
    apiType: "openai-compatible",
    freeTier: "30 RPM, 2K req/day, phone verification",
    description: "256K context, code-focused",
  },
  {
    id: "llm7",
    name: "LLM7.io",
    baseURL: "https://api.llm7.io/v1",
    envKey: "LLM7_API_KEY",
    website: "https://llm7.io",
    apiType: "openai-compatible",
    freeTier: "30 RPM (120 RPM with free token), no CC",
    noCc: true,
    permanentFree: true,
    description: "GDPR-compliant",
  },
  {
    id: "kilo-code",
    name: "Kilo Code",
    baseURL: "https://api.kilo.ai/api/gateway",
    envKey: "KILO_API_KEY",
    website: "https://kilo.ai",
    apiType: "openai-compatible",
    freeTier: "~200 req/hr, free auto-router",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseURL: "https://openrouter.ai/api/v1",
    envKey: "OPENROUTER_API_KEY",
    website: "https://openrouter.ai",
    apiType: "openai-compatible",
    freeTier: "50-200 RPD on :free models, 22+ free models",
    permanentFree: true,
  },
  {
    id: "sambanova",
    name: "SambaNova",
    baseURL: "https://api.sambanova.ai/v1",
    envKey: "SAMBANOVA_API_KEY",
    website: "https://cloud.sambanova.ai",
    apiType: "openai-compatible",
    freeTier: "20 RPM, 20 RPD, 200K TPD + $5 credits",
    permanentFree: true,
  },
  {
    id: "cohere",
    name: "Cohere",
    baseURL: "https://api.cohere.com/v2",
    envKey: "COHERE_API_KEY",
    website: "https://dashboard.cohere.com",
    apiType: "openai-compatible",
    freeTier: "1000 calls/month Trial, 20 RPM, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    baseURL: "https://api.ai21.com/studio/v1",
    envKey: "AI21_API_KEY",
    website: "https://studio.ai21.com",
    apiType: "openai-compatible",
    freeTier: "200 RPM, 10 RPS, no CC",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "siliconflow",
    name: "SiliconFlow (硅基流动)",
    baseURL: "https://api.siliconflow.cn/v1",
    envKey: "SILICONFLOW_API_KEY",
    website: "https://siliconflow.cn",
    apiType: "openai-compatible",
    freeTier: "30 RPM, 60K TPM on free models",
    permanentFree: true,
  },
  {
    id: "modelscope",
    name: "ModelScope (魔搭)",
    baseURL: "https://api-inference.modelscope.cn/v1",
    envKey: "MODELSCOPE_API_KEY",
    website: "https://modelscope.cn",
    apiType: "openai-compatible",
    freeTier: "2000 RPD, ≤500 RPD/model",
    permanentFree: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseURL: "https://api.deepseek.com/v1",
    envKey: "DEEPSEEK_API_KEY",
    website: "https://platform.deepseek.com",
    apiType: "openai-compatible",
    freeTier: "Dynamic rate limits",
    permanentFree: true,
  },
  {
    id: "glhf",
    name: "Glhf.chat",
    baseURL: "https://glhf.chat/api/openai/v1",
    envKey: "GLHF_API_KEY",
    website: "https://glhf.chat",
    apiType: "openai-compatible",
    freeTier: "Unlimited for free models",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "chutes",
    name: "Chutes.ai",
    baseURL: "https://api.chutes.ai/v1",
    envKey: "CHUTES_API_KEY",
    website: "https://chutes.ai",
    apiType: "openai-compatible",
    freeTier: "Community-powered, no hard cap",
    permanentFree: true,
  },
  {
    id: "kluster",
    name: "Kluster.ai",
    baseURL: "https://api.kluster.ai/v1",
    envKey: "KLUSTER_API_KEY",
    website: "https://kluster.ai",
    apiType: "openai-compatible",
    freeTier: "Batch-based, free for API",
    permanentFree: true,
    description: "Llama 3.1 405B free tier",
  },
  {
    id: "nscale",
    name: "Nscale",
    baseURL: "https://inference.api.nscale.com/v1",
    envKey: "NSCALE_API_KEY",
    website: "https://console.nscale.com",
    apiType: "openai-compatible",
    freeTier: "Fair-use free tier",
    permanentFree: true,
  },
  {
    id: "inference-net",
    name: "Inference.net",
    baseURL: "https://api.inference.net/v1",
    envKey: "INFERENCE_NET_API_KEY",
    website: "https://inference.net",
    apiType: "openai-compatible",
    freeTier: "Free for listed models",
    permanentFree: true,
  },
  {
    id: "pollinations",
    name: "Pollinations AI",
    baseURL: "https://gen.pollinations.ai",
    website: "https://pollinations.ai",
    apiType: "openai-compatible",
    freeTier: "Free, no API key needed",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "puter",
    name: "Puter",
    baseURL: "https://puter.com/api/llm",
    website: "https://puter.com",
    apiType: "openai-compatible",
    freeTier: "Free, no signup",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "scaleway",
    name: "Scaleway Generative APIs",
    baseURL: "https://api.scaleway.ai/v1",
    envKey: "SCALEWAY_API_KEY",
    website: "https://console.scaleway.com",
    apiType: "openai-compatible",
    freeTier: "1M free tokens",
    permanentFree: true,
  },
  {
    id: "nebulous",
    name: "Nebius AI Studio",
    baseURL: "https://api.studio.nebius.ai/v1",
    envKey: "NEBIUS_API_KEY",
    website: "https://studio.nebius.ai",
    apiType: "openai-compatible",
    freeTier: "Tier-based free access",
    permanentFree: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    baseURL: "https://api.openai.com/v1",
    envKey: "OPENAI_API_KEY",
    website: "https://platform.openai.com",
    apiType: "openai",
    freeTier: "$5 free credits (90 day expiry)",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseURL: "https://api.anthropic.com/v1",
    envKey: "ANTHROPIC_API_KEY",
    website: "https://console.anthropic.com",
    apiType: "anthropic",
    freeTier: "Usage credits with Claude subscription",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    baseURL: "https://api.x.ai/v1",
    envKey: "XAI_API_KEY",
    website: "https://console.x.ai",
    apiType: "openai-compatible",
    freeTier: "$25/month free credits for Grok-2",
    description: "2M context",
  },
  {
    id: "together",
    name: "Together AI",
    baseURL: "https://api.together.xyz/v1",
    envKey: "TOGETHER_API_KEY",
    website: "https://together.ai",
    apiType: "openai-compatible",
    freeTier: "$5 free credits, 100+ models",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    baseURL: "https://api.fireworks.ai/inference/v1",
    envKey: "FIREWORKS_API_KEY",
    website: "https://fireworks.ai",
    apiType: "openai-compatible",
    freeTier: "$1 free credits, 10 RPM without payment",
  },
  {
    id: "deepinfra",
    name: "Deep Infra",
    baseURL: "https://api.deepinfra.com/v1/openai",
    envKey: "DEEPINFRA_API_KEY",
    website: "https://deepinfra.com",
    apiType: "openai-compatible",
    freeTier: "Free credits on signup, 200 concurrent requests",
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    baseURL: "https://api.hyperbolic.xyz/v1",
    envKey: "HYPERBOLIC_API_KEY",
    website: "https://app.hyperbolic.ai",
    apiType: "openai-compatible",
    freeTier: "$1 free credits (permanent)",
    permanentFree: true,
  },
  {
    id: "novita",
    name: "Novita AI",
    baseURL: "https://api.novita.ai/openai",
    envKey: "NOVITA_API_KEY",
    website: "https://novita.ai",
    apiType: "openai-compatible",
    freeTier: "$0.50 free credits/month",
  },
  {
    id: "dashscope",
    name: "DashScope / Alibaba (灵积)",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    envKey: "DASHSCOPE_API_KEY",
    website: "https://bailian.console.alibabacloud.com",
    apiType: "openai-compatible",
    freeTier: "1M free tokens per model (90 days)",
  },
  {
    id: "modal",
    name: "Modal",
    baseURL: "https://api.modal.com/v1",
    envKey: "MODAL_API_KEY",
    website: "https://modal.com",
    apiType: "openai-compatible",
    freeTier: "$30/month free credits",
  },
  {
    id: "replicate",
    name: "Replicate",
    baseURL: "https://api.replicate.com/v1",
    envKey: "REPLICATE_API_TOKEN",
    website: "https://replicate.com",
    apiType: "openai-compatible",
    freeTier: "Development quota",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    baseURL: "https://api.perplexity.ai/v1",
    envKey: "PERPLEXITY_API_KEY",
    website: "https://www.perplexity.ai",
    apiType: "openai-compatible",
    freeTier: "~50 RPM free tier",
  },
  {
    id: "baseten",
    name: "Baseten",
    baseURL: "https://app.baseten.co/v1",
    envKey: "BASETEN_API_KEY",
    website: "https://baseten.co",
    apiType: "openai-compatible",
    freeTier: "Trial credits available",
  },
  {
    id: "upstage",
    name: "Upstage AI (Solar)",
    baseURL: "https://api.upstage.ai/v1/solar",
    envKey: "UPSTAGE_API_KEY",
    website: "https://upstage.ai",
    apiType: "openai-compatible",
    freeTier: "Trial credits available",
  },
  {
    id: "aiml-api",
    name: "AIML API",
    baseURL: "https://api.aimlapi.com/v1",
    envKey: "AIML_API_KEY",
    website: "https://aimlapi.com",
    apiType: "openai-compatible",
    freeTier: "Free tier, 200+ models",
  },
  {
    id: "coze",
    name: "Coze",
    baseURL: "https://api.coze.com/v1",
    envKey: "COZE_API_KEY",
    website: "https://coze.com",
    apiType: "openai-compatible",
    freeTier: "Free daily tokens",
  },
  {
    id: "moonshot",
    name: "Moonshot AI / Kimi (月之暗面)",
    baseURL: "https://api.moonshot.cn/v1",
    envKey: "MOONSHOT_API_KEY",
    website: "https://platform.moonshot.cn",
    apiType: "openai-compatible",
  },
  {
    id: "minimax",
    name: "MiniMax (稀宇)",
    baseURL: "https://api.minimax.chat/v1",
    envKey: "MINIMAX_API_KEY",
    website: "https://platform.minimax.chat",
    apiType: "openai-compatible",
  },
  {
    id: "baichuan",
    name: "Baichuan AI (百川)",
    baseURL: "https://api.baichuan-ai.com/v1",
    envKey: "BAICHUAN_API_KEY",
    website: "https://platform.baichuan-ai.com",
    apiType: "openai-compatible",
  },
  {
    id: "stepfun",
    name: "Stepfun / Step (阶跃星辰)",
    baseURL: "https://api.stepfun.com/v1",
    envKey: "STEPFUN_API_KEY",
    website: "https://platform.stepfun.com",
    apiType: "openai-compatible",
  },
  {
    id: "lingyi",
    name: "Lingyiwanwu / 01.AI (零一万物)",
    baseURL: "https://api.lingyiwanwu.com/v1",
    envKey: "LINGYI_API_KEY",
    website: "https://platform.lingyiwanwu.com",
    apiType: "openai-compatible",
  },
  {
    id: "baidu",
    name: "Baidu ERNIE (文心)",
    baseURL: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat",
    envKey: "BAIDU_API_KEY",
    website: "https://cloud.baidu.com",
    apiType: "openai-compatible",
  },
  {
    id: "tencent",
    name: "Tencent Hunyuan (混元)",
    baseURL: "https://api.hunyuan.cloud.tencent.com/v1",
    envKey: "TENCENT_API_KEY",
    website: "https://hunyuan.tencent.com",
    apiType: "openai-compatible",
  },
  {
    id: "volcengine",
    name: "ByteDance Volcengine / Ark (火山引擎)",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    envKey: "VOLC_API_KEY",
    website: "https://console.volcengine.com/ark",
    apiType: "openai-compatible",
  },
  {
    id: "sensetime",
    name: "SenseTime / SenseNova (商汤)",
    baseURL: "https://api.sensenova.cn/v1",
    envKey: "SENSENOVA_API_KEY",
    website: "https://platform.sensenova.cn",
    apiType: "openai-compatible",
  },
  {
    id: "baidu-qianfan",
    name: "Baidu Qianfan (千帆)",
    baseURL: "https://qianfan.baidubce.com/v2",
    envKey: "QIANFAN_API_KEY",
    website: "https://console.bce.baidu.com/qianfan",
    apiType: "openai-compatible",
  },
  {
    id: "iflytek",
    name: "iFlytek Spark (讯飞星火)",
    baseURL: "https://spark-api.xf-yun.com/v3.5/chat",
    envKey: "IFLYTEK_API_KEY",
    website: "https://xinghuo.xfyun.cn",
    apiType: "openai-compatible",
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    baseURL: "https://{resource}.openai.azure.com/openai",
    envKey: "AZURE_OPENAI_API_KEY",
    website: "https://portal.azure.com",
    apiType: "openai",
    freeTier: "$200 Azure free credits (30 days)",
  },
  {
    id: "aws-bedrock",
    name: "Amazon Bedrock",
    baseURL: "https://bedrock-runtime.{region}.amazonaws.com",
    envKey: "AWS_ACCESS_KEY_ID",
    website: "https://aws.amazon.com/bedrock",
    apiType: "openai-compatible",
    freeTier: "Free tier with AWS Free Tier",
  },
  {
    id: "gcp-vertex",
    name: "Google Vertex AI",
    baseURL: "https://{region}-aiplatform.googleapis.com/v1",
    envKey: "GOOGLE_APPLICATION_CREDENTIALS",
    website: "https://console.cloud.google.com/vertex-ai",
    apiType: "openai-compatible",
    freeTier: "$300 Google Cloud free credits",
  },
  {
    id: "cloudflare-gateway",
    name: "Cloudflare AI Gateway",
    baseURL: "https://gateway.ai.cloudflare.com/v1/{account}/{gateway}",
    envKey: "CLOUDFLARE_API_TOKEN",
    website: "https://dash.cloudflare.com",
    apiType: "openai-compatible",
    freeTier: "Free tier with Cloudflare account",
  },
  {
    id: "vercel-gateway",
    name: "Vercel AI Gateway",
    baseURL: "https://gateway.vercel.ai/v1",
    envKey: "VERCEL_API_TOKEN",
    website: "https://vercel.com",
    apiType: "openai-compatible",
    freeTier: "Free tier through Vercel",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean Inference",
    baseURL: "https://{region}.inference.digitalocean.com/v1",
    envKey: "DIGITALOCEAN_ACCESS_TOKEN",
    website: "https://cloud.digitalocean.com",
    apiType: "openai-compatible",
    freeTier: "$200 free credits (60 days)",
  },
  {
    id: "oci",
    name: "Oracle Cloud OCI Generative AI",
    baseURL: "https://inference.generativeai.{region}.oci.oraclecloud.com/v1",
    envKey: "OCI_API_KEY",
    website: "https://cloud.oracle.com",
    apiType: "openai-compatible",
    freeTier: "Always Free tier + $300 trial",
  },
  {
    id: "helicone",
    name: "Helicone AI Gateway",
    baseURL: "https://ai-gateway.helicone.ai/v1",
    envKey: "HELICONE_API_KEY",
    website: "https://helicone.ai",
    apiType: "openai-compatible",
    freeTier: "100K requests/month free",
    permanentFree: true,
  },
  {
    id: "portkey",
    name: "Portkey AI Gateway",
    baseURL: "https://api.portkey.ai/v1",
    envKey: "PORTKEY_API_KEY",
    website: "https://portkey.ai",
    apiType: "openai-compatible",
    freeTier: "10K requests/month free",
    permanentFree: true,
  },
  {
    id: "litellm",
    name: "LiteLLM Proxy",
    baseURL: "http://localhost:4000/v1",
    envKey: "LITELLM_API_KEY",
    website: "https://litellm.ai",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "browserai",
    name: "BrowserAI",
    baseURL: "https://api.browserai.com/v1",
    envKey: "BROWSERAI_API_KEY",
    website: "https://browserai.com",
    apiType: "openai-compatible",
  },
  {
    id: "llmgateway",
    name: "LLM Gateway",
    baseURL: "https://api.llmgateway.io/v1",
    envKey: "LLMGATEWAY_API_KEY",
    website: "https://llmgateway.io",
    apiType: "openai-compatible",
  },
  {
    id: "adaline",
    name: "Adaline AI Gateway",
    baseURL: "https://gateway.adaline.ai/v1",
    envKey: "ADALINE_API_KEY",
    website: "https://adaline.ai",
    apiType: "openai-compatible",
  },
  {
    id: "routeway",
    name: "Routeway",
    baseURL: "https://api.routeway.ai/v1",
    envKey: "ROUTEWAY_API_KEY",
    website: "https://routeway.ai",
    apiType: "openai-compatible",
    freeTier: ":free zero-price models",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "anyscale",
    name: "Anyscale Endpoints",
    baseURL: "https://api.endpoints.anyscale.com/v1",
    envKey: "ANYSCALE_API_KEY",
    website: "https://anyscale.com",
    apiType: "openai-compatible",
  },
  {
    id: "banana",
    name: "Banana ML",
    baseURL: "https://api.banana.dev/v1",
    envKey: "BANANA_API_KEY",
    website: "https://banana.dev",
    apiType: "openai-compatible",
  },
  {
    id: "cuttle",
    name: "Cuttle AI",
    baseURL: "https://api.cuttle.ai/v1",
    envKey: "CUTTLE_API_KEY",
    website: "https://cuttle.ai",
    apiType: "openai-compatible",
  },
  {
    id: "infermatic",
    name: "Infermatic AI",
    baseURL: "https://api.infermatic.ai/v1",
    envKey: "INFERMATIC_API_KEY",
    website: "https://infermatic.ai",
    apiType: "openai-compatible",
  },
  {
    id: "mancer",
    name: "Mancer AI",
    baseURL: "https://api.mancer.ai/v1",
    envKey: "MANCER_API_KEY",
    website: "https://mancer.ai",
    apiType: "openai-compatible",
  },
  {
    id: "monsterapi",
    name: "Monster API",
    baseURL: "https://llm.monsterapi.ai/v1",
    envKey: "MONSTER_API_KEY",
    website: "https://monsterapi.ai",
    apiType: "openai-compatible",
  },
  {
    id: "dreamfactory",
    name: "DreamFactory AI",
    baseURL: "https://api.dreamfactory.ai/v1",
    envKey: "DREAMFACTORY_API_KEY",
    website: "https://dreamfactory.ai",
    apiType: "openai-compatible",
  },
  {
    id: "anya",
    name: "Anya AI",
    baseURL: "https://api.anya.ai/v1",
    envKey: "ANYA_API_KEY",
    website: "https://anya.ai",
    apiType: "openai-compatible",
  },
  {
    id: "khoj",
    name: "Khoj AI",
    baseURL: "https://api.khoj.dev/v1",
    envKey: "KHOJ_API_KEY",
    website: "https://khoj.dev",
    apiType: "openai-compatible",
  },
  {
    id: "ollama",
    name: "Ollama",
    baseURL: "http://localhost:11434/v1",
    website: "https://ollama.com",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted), 100+ models",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    baseURL: "https://api.ollama.com",
    envKey: "OLLAMA_API_KEY",
    website: "https://ollama.com/pricing",
    apiType: "openai-compatible",
    freeTier: "Free cloud usage",
    permanentFree: true,
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    baseURL: "http://localhost:1234/v1",
    website: "https://lmstudio.ai",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "llamacpp",
    name: "llama.cpp",
    baseURL: "http://localhost:8080/v1",
    website: "https://github.com/ggml-org/llama.cpp",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "vllm",
    name: "vLLM",
    baseURL: "http://localhost:8000/v1",
    website: "https://github.com/vllm-project/vllm",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "localai",
    name: "LocalAI",
    baseURL: "http://localhost:8080/v1",
    website: "https://localai.io",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "text-gen-ui",
    name: "Text Generation WebUI (oobabooga)",
    baseURL: "http://localhost:5000/v1",
    website: "https://github.com/oobabooga/text-generation-webui",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "tabbyapi",
    name: "TabbyAPI",
    baseURL: "http://localhost:5000/v1",
    website: "https://github.com/theroyallab/tabbyAPI",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "aphrodite",
    name: "Aphrodite Engine",
    baseURL: "http://localhost:2242/v1",
    website: "https://github.com/PygmalionAI/aphrodite-engine",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "kobold",
    name: "KoboldCpp",
    baseURL: "http://localhost:5001/v1",
    website: "https://github.com/LostRuins/koboldcpp",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "gpt4all",
    name: "GPT4All",
    baseURL: "http://localhost:4891/v1",
    website: "https://gpt4all.io",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local), CPU-only",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "jan",
    name: "Jan.ai",
    baseURL: "http://localhost:1337/v1",
    website: "https://jan.ai",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local), offline",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "atomic-chat",
    name: "Atomic Chat",
    baseURL: "http://127.0.0.1:1337/v1",
    website: "https://atomic.chat",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "aleph-alpha",
    name: "Aleph Alpha",
    baseURL: "https://api.aleph-alpha.com/v1",
    envKey: "ALEPH_ALPHA_API_KEY",
    website: "https://www.aleph-alpha.com",
    apiType: "openai-compatible",
    description: "European sovereign AI",
  },
  {
    id: "deepset",
    name: "Deepset Cloud",
    baseURL: "https://api.deepset.ai/v1",
    envKey: "DEEPSET_API_KEY",
    website: "https://www.deepset.ai",
    apiType: "openai-compatible",
  },
  {
    id: "jina",
    name: "Jina AI",
    baseURL: "https://api.jina.ai/v1",
    envKey: "JINA_API_KEY",
    website: "https://jina.ai",
    apiType: "openai-compatible",
  },
  {
    id: "nomic",
    name: "Nomic AI",
    baseURL: "https://api.nomic.ai/v1",
    envKey: "NOMIC_API_KEY",
    website: "https://nomic.ai",
    apiType: "openai-compatible",
  },
  {
    id: "nlpcloud",
    name: "NLP Cloud",
    baseURL: "https://api.nlpcloud.io/v1",
    envKey: "NLPCLOUD_API_KEY",
    website: "https://nlpcloud.com",
    apiType: "openai-compatible",
    freeTier: "Trial credits available",
  },
  {
    id: "sakana",
    name: "Sakana AI",
    baseURL: "https://api.sakana.ai/v1",
    envKey: "SAKANA_API_KEY",
    website: "https://sakana.ai",
    apiType: "openai-compatible",
  },
  {
    id: "stockmark",
    name: "Stockmark",
    baseURL: "https://api.stockmark.ai/v1",
    envKey: "STOCKMARK_API_KEY",
    website: "https://stockmark.ai",
    apiType: "openai-compatible",
  },
  {
    id: "elyza",
    name: "Elyza LLM",
    baseURL: "https://api.elyza.ai/v1",
    envKey: "ELYZA_API_KEY",
    website: "https://elyza.ai",
    apiType: "openai-compatible",
  },
  {
    id: "naver",
    name: "Naver HyperCLOVA",
    baseURL: "https://clovastudio.apigw.ntruss.com/v1",
    envKey: "NAVER_API_KEY",
    website: "https://www.ncloud.com",
    apiType: "openai-compatible",
  },
  {
    id: "kakao",
    name: "Kakao Brain",
    baseURL: "https://api.kakaobrain.com/v1",
    envKey: "KAKAO_API_KEY",
    website: "https://kakaobrain.com",
    apiType: "openai-compatible",
  },
  {
    id: "lg-ai",
    name: "LG AI (EXAONE)",
    baseURL: "https://api.lg-ai.com/v1",
    envKey: "LG_AI_API_KEY",
    website: "https://lg-ai.com",
    apiType: "openai-compatible",
  },
  {
    id: "aispace",
    name: "AI Singapore (SEA-LION)",
    baseURL: "https://api.aisingapore.org/v1",
    envKey: "AISG_API_KEY",
    website: "https://aisingapore.org",
    apiType: "openai-compatible",
  },
  {
    id: "core42",
    name: "Core42 / G42 (UAE)",
    baseURL: "https://api.core42.ai/v1",
    envKey: "CORE42_API_KEY",
    website: "https://core42.ai",
    apiType: "openai-compatible",
  },
  {
    id: "tii",
    name: "TII (Falcon / UAE)",
    baseURL: "https://api.tii.ae/v1",
    envKey: "TII_API_KEY",
    website: "https://tii.ae",
    apiType: "openai-compatible",
  },
  {
    id: "froog",
    name: "Froog AI",
    baseURL: "https://api.froog.ai/v1",
    envKey: "FROOG_API_KEY",
    website: "https://froog.ai",
    apiType: "openai-compatible",
  },
  {
    id: "mendable",
    name: "Mendable",
    baseURL: "https://api.mendable.ai/v1",
    envKey: "MENDABLE_API_KEY",
    website: "https://mendable.ai",
    apiType: "openai-compatible",
  },
  {
    id: "fiddle",
    name: "Fiddle AI",
    baseURL: "https://api.fiddle.ai/v1",
    envKey: "FIDDLE_API_KEY",
    website: "https://fiddle.ai",
    apiType: "openai-compatible",
  },
  {
    id: "triton",
    name: "Triton AI",
    baseURL: "https://api.triton.ai/v1",
    envKey: "TRITON_API_KEY",
    website: "https://triton.ai",
    apiType: "openai-compatible",
  },
  {
    id: "shuttleai",
    name: "Shuttle AI",
    baseURL: "https://api.shuttle.ai/v1",
    envKey: "SHUTTLE_API_KEY",
    website: "https://shuttle.ai",
    apiType: "openai-compatible",
  },
  {
    id: "chatllm",
    name: "ChatLLM (Abacus)",
    baseURL: "https://api.chatllm.com/v1",
    envKey: "CHATLLM_API_KEY",
    website: "https://chatllm.com",
    apiType: "openai-compatible",
  },

  // ── From provider-search.md: US/European Providers ──────────────
  {
    id: "kimchi",
    name: "Kimchi Inference",
    baseURL: "https://llm.kimchi.dev/openai/v1",
    envKey: "KIMCHI_API_KEY",
    website: "https://kimchi.dev",
    apiType: "openai-compatible",
    freeTier: "$50/mo free credits for developers",
    permanentFree: true,
  },
  {
    id: "tokenrouter",
    name: "TokenRouter",
    baseURL: "https://api.tokenrouter.io/v1",
    envKey: "TOKENROUTER_API_KEY",
    website: "https://tokenrouter.io",
    apiType: "openai-compatible",
    freeTier: "Free MiniMax M3 API access",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "aerolink",
    name: "Aerolink",
    baseURL: "https://aerolink.lat",
    envKey: "AEROLINK_API_KEY",
    website: "https://aerolink.lat",
    apiType: "openai-compatible",
    freeTier: "Free $350+ rolling credits ($10/5 hours)",
    permanentFree: true,
  },
  {
    id: "b-ai",
    name: "B.AI",
    baseURL: "https://api.b.ai/v1",
    envKey: "BAI_API_KEY",
    website: "https://b.ai",
    apiType: "openai-compatible",
    freeTier: "500K credits on signup, no card",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "lightning-ai",
    name: "Lightning AI Models",
    baseURL: "https://api.lightning.ai/v1",
    envKey: "LIGHTNING_API_KEY",
    website: "https://lightning.ai",
    apiType: "openai-compatible",
    freeTier: "15 free credits/mo ($15 value, up to 30M tokens)",
    permanentFree: true,
  },
  {
    id: "aion-labs",
    name: "Aion Labs",
    baseURL: "https://api.aionlabs.ai/v1",
    envKey: "AION_API_KEY",
    website: "https://aionlabs.ai",
    apiType: "openai-compatible",
    freeTier: "Daily free token allowance on registration",
    permanentFree: true,
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    baseURL: "https://opencode.ai/zen/v1",
    envKey: "OPENCODE_ZEN_API_KEY",
    website: "https://opencode.ai/zen",
    apiType: "openai-compatible",
    freeTier: "Free curated gateway",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "lepton",
    name: "Lepton AI",
    baseURL: "https://api.lepton.ai/v1",
    envKey: "LEPTON_API_KEY",
    website: "https://lepton.ai",
    apiType: "openai-compatible",
    freeTier: "$10 free trial credits for developers",
    permanentFree: true,
  },
  {
    id: "friendli",
    name: "Friendli AI",
    baseURL: "https://api.friendli.ai/v1",
    envKey: "FRIENDLI_API_KEY",
    website: "https://friendli.ai",
    apiType: "openai-compatible",
    freeTier: "$10 free trial credits",
    permanentFree: true,
  },
  {
    id: "cerebrium",
    name: "Cerebrium",
    baseURL: "https://api.cerebrium.ai/v1",
    envKey: "CEREBRIUM_API_KEY",
    website: "https://cerebrium.ai",
    apiType: "openai-compatible",
    freeTier: "$30 free trial credits",
    permanentFree: true,
  },
  {
    id: "requesty",
    name: "Requesty",
    baseURL: "https://api.requesty.ai/v1",
    envKey: "REQUESTY_API_KEY",
    website: "https://requesty.ai",
    apiType: "openai-compatible",
    freeTier: "Free monthly credit allocations",
    permanentFree: true,
  },
  {
    id: "zenmux",
    name: "ZenMux",
    baseURL: "https://api.zenmux.com/v1",
    envKey: "ZENMUX_API_KEY",
    website: "https://zenmux.com",
    apiType: "openai-compatible",
    freeTier: "Free sandbox API tier",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "crofai",
    name: "CrofAI",
    baseURL: "https://api.crofai.com/v1",
    envKey: "CROFAI_API_KEY",
    website: "https://crofai.com",
    apiType: "openai-compatible",
    freeTier: "Promo credits at registration",
    permanentFree: true,
  },
  {
    id: "fastrouter",
    name: "FastRouter",
    baseURL: "https://api.fastrouter.ai/v1",
    envKey: "FASTROUTER_API_KEY",
    website: "https://fastrouter.ai",
    apiType: "openai-compatible",
    freeTier: "Trial credits",
    permanentFree: true,
  },
  {
    id: "aiqu",
    name: "AiQu",
    baseURL: "https://api.aiqu.se/v1",
    envKey: "AIQU_API_KEY",
    website: "https://aiqu.se",
    apiType: "openai-compatible",
    freeTier: "Swedish cloud free sandbox",
    noCc: true,
    permanentFree: true,
    description: "EU sovereign hosted",
  },
  {
    id: "airon",
    name: "Airon",
    baseURL: "https://api.airon.io/v1",
    envKey: "AIRON_API_KEY",
    website: "https://airon.io",
    apiType: "openai-compatible",
    freeTier: "Serverless trial credits",
    permanentFree: true,
  },
  {
    id: "aki",
    name: "AKI.IO",
    baseURL: "https://api.aki.io/v1",
    envKey: "AKI_API_KEY",
    website: "https://aki.io",
    apiType: "openai-compatible",
    freeTier: "10 EUR trial credits",
    permanentFree: true,
  },
  {
    id: "ark-labs",
    name: "ARK Labs",
    baseURL: "https://api.arklabs.ai/v1",
    envKey: "ARK_API_KEY",
    website: "https://arklabs.ai",
    apiType: "openai-compatible",
    freeTier: "EU sovereign free tier",
    noCc: true,
    permanentFree: true,
    description: "Regulated environment models",
  },
  {
    id: "beam",
    name: "Beam",
    baseURL: "https://api.beam.cloud/v1",
    envKey: "BEAM_API_KEY",
    website: "https://beam.cloud",
    apiType: "openai-compatible",
    freeTier: "Serverless GPU free trial tier",
    permanentFree: true,
  },
  {
    id: "bentocloud",
    name: "BentoCloud",
    baseURL: "https://api.bentocloud.com/v1",
    envKey: "BENTOML_API_KEY",
    website: "https://bentoml.com",
    apiType: "openai-compatible",
    freeTier: "Free trial credits",
    permanentFree: true,
  },
  {
    id: "berget",
    name: "Berget AI",
    baseURL: "https://api.berget.ai/v1",
    envKey: "BERGET_API_KEY",
    website: "https://berget.ai",
    apiType: "openai-compatible",
    freeTier: "EU sovereign free tier",
    noCc: true,
    permanentFree: true,
    description: "EU compliant models",
  },
  {
    id: "cortecs",
    name: "Cortecs AI",
    baseURL: "https://api.cortecs.ai/v1",
    envKey: "CORTECS_API_KEY",
    website: "https://cortecs.ai",
    apiType: "openai-compatible",
    freeTier: "Gateway free trial",
    permanentFree: true,
  },
  {
    id: "eurouter",
    name: "EUrouter",
    baseURL: "https://api.eurouter.com/v1",
    envKey: "EUROUTER_API_KEY",
    website: "https://eurouter.com",
    apiType: "openai-compatible",
    freeTier: "1K requests/month free",
    noCc: true,
    permanentFree: true,
    description: "100+ GDPR models",
  },
  {
    id: "infercom",
    name: "Infercom",
    baseURL: "https://api.infercom.ai/v1",
    envKey: "INFERCOM_API_KEY",
    website: "https://infercom.ai",
    apiType: "openai-compatible",
    freeTier: "Free tier, EU hosted",
    noCc: true,
    permanentFree: true,
    description: "Sovereign open models",
  },
  {
    id: "ionrouter",
    name: "IonRouter",
    baseURL: "https://api.ionrouter.com/v1",
    envKey: "IONROUTER_API_KEY",
    website: "https://ionrouter.com",
    apiType: "openai-compatible",
    freeTier: "Free tier options",
    permanentFree: true,
  },
  {
    id: "lambda",
    name: "Lambda AI",
    baseURL: "https://api.lambdalabs.com/v1",
    envKey: "LAMBDA_API_KEY",
    website: "https://lambdalabs.com",
    apiType: "openai-compatible",
    freeTier: "Trial cloud credits",
    permanentFree: true,
  },
  {
    id: "octoai",
    name: "OctoAI",
    baseURL: "https://api.octoai.cloud/v1",
    envKey: "OCTOAI_API_KEY",
    website: "https://octoai.cloud",
    apiType: "openai-compatible",
    freeTier: "Free trial credits",
    permanentFree: true,
  },
  {
    id: "prem",
    name: "Prem AI",
    baseURL: "https://api.premai.io/v1",
    envKey: "PREM_API_KEY",
    website: "https://premai.io",
    apiType: "openai-compatible",
    freeTier: "Free tier",
    permanentFree: true,
  },
  {
    id: "synexa",
    name: "Synexa",
    baseURL: "https://api.synexa.io/v1",
    envKey: "SYNEXA_API_KEY",
    website: "https://synexa.io",
    apiType: "openai-compatible",
    freeTier: "Trial credits, $0.0015/image",
    permanentFree: true,
  },
  {
    id: "tokenware",
    name: "Tokenware",
    baseURL: "https://api.tokenware.io/v1",
    envKey: "TOKENWARE_API_KEY",
    website: "https://tokenware.io",
    apiType: "openai-compatible",
    freeTier: "Free trial credits, 200+ models",
    permanentFree: true,
  },
  {
    id: "voyage",
    name: "Voyage AI",
    baseURL: "https://api.voyageai.com/v1",
    envKey: "VOYAGE_API_KEY",
    website: "https://voyageai.com",
    apiType: "openai-compatible",
    freeTier: "Free tier credits available",
    permanentFree: true,
    description: "High quality embeddings",
  },
  {
    id: "featherless",
    name: "Featherless AI",
    baseURL: "https://api.featherless.ai/v1",
    envKey: "FEATHERLESS_API_KEY",
    website: "https://featherless.ai",
    apiType: "openai-compatible",
    freeTier: "Free tier trial, 200+ open-source models",
    permanentFree: true,
  },
  {
    id: "morph",
    name: "Morph",
    baseURL: "https://api.morph.chat/v1",
    envKey: "MORPH_API_KEY",
    website: "https://morph.chat",
    apiType: "openai-compatible",
    freeTier: "Agentic free credits",
    permanentFree: true,
  },
  {
    id: "predibase",
    name: "Predibase",
    baseURL: "https://connect.predibase.com/v1",
    envKey: "PREDIBASE_API_KEY",
    website: "https://predibase.com",
    apiType: "openai-compatible",
    freeTier: "Free credits on signup",
    permanentFree: true,
    description: "Custom fine-tuned LoRA models",
  },
  {
    id: "ferryapi",
    name: "FerryAPI",
    baseURL: "https://api.ferryapi.com/v1",
    envKey: "FERRYAPI_API_KEY",
    website: "https://ferryapi.com",
    apiType: "openai-compatible",
    freeTier: "Prepay signup bonus",
    permanentFree: true,
  },
  {
    id: "fastpivot",
    name: "Fast Pivot",
    baseURL: "https://api.fastpivot.io/v1",
    envKey: "FASTPIVOT_API_KEY",
    website: "https://fastpivot.io",
    apiType: "openai-compatible",
    freeTier: "Prepaid credit trial",
    permanentFree: true,
  },
  {
    id: "general-compute",
    name: "General Compute",
    baseURL: "https://api.generalcompute.com/v1",
    envKey: "GENERAL_COMPUTE_API_KEY",
    website: "https://generalcompute.com",
    apiType: "openai-compatible",
    freeTier: "Trial compute hours",
    permanentFree: true,
    description: "Latency-critical coding models",
  },
  {
    id: "coreweave",
    name: "CoreWeave",
    baseURL: "https://api.coreweave.com/v1",
    envKey: "COREWEAVE_API_KEY",
    website: "https://coreweave.com",
    apiType: "openai-compatible",
    freeTier: "Trial cloud credits",
    permanentFree: true,
  },
  {
    id: "venice",
    name: "Venice.ai",
    baseURL: "https://api.venice.ai/api/v1",
    envKey: "VENICE_API_KEY",
    website: "https://venice.ai",
    apiType: "openai-compatible",
    freeTier: "Daily limits allowed for free tier",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "packet",
    name: "Packet.ai",
    baseURL: "https://api.packet.ai/v1",
    envKey: "PACKET_API_KEY",
    website: "https://packet.ai",
    apiType: "openai-compatible",
    freeTier: "Billed per token, trial credits",
    permanentFree: true,
  },
  {
    id: "verda",
    name: "Verda",
    baseURL: "https://api.verda.ai/v1",
    envKey: "VERDA_API_KEY",
    website: "https://verda.ai",
    apiType: "openai-compatible",
    freeTier: "Serverless trial",
    permanentFree: true,
    description: "European optimized LLMs",
  },

  // ── From provider-search.md: Chinese/Asian Providers ────────────
  {
    id: "yi",
    name: "Yi AI / 01.AI (零一万物)",
    baseURL: "https://api.01.ai/v1",
    envKey: "YI_API_KEY",
    website: "https://01.ai",
    apiType: "openai-compatible",
    freeTier: "Initial trial credits on signup",
    permanentFree: true,
  },
  {
    id: "mimo",
    name: "Xiaomi Mimo (小米)",
    baseURL: "https://api.mimo.xiaomi.com/v1",
    envKey: "MIMO_API_KEY",
    website: "https://mi.com",
    apiType: "openai-compatible",
    freeTier: "Highly competitive pricing ($0.14/1M)",
    permanentFree: true,
  },
  {
    id: "streamlake",
    name: "StreamLake / Kuaishou (快手)",
    baseURL: "https://api.streamlake.com/v1",
    envKey: "STREAMLAKE_API_KEY",
    website: "https://streamlake.com",
    apiType: "openai-compatible",
    freeTier: "Developer trial credits",
    permanentFree: true,
  },
  {
    id: "gitee-ai",
    name: "Gitee AI (码云)",
    baseURL: "https://ai.gitee.com/v1",
    envKey: "GITEE_AI_TOKEN",
    website: "https://gitee.com/ai",
    apiType: "openai-compatible",
    freeTier: "Developer free sandbox tokens",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "linkos",
    name: "Linkos AI",
    baseURL: "https://api.linkos.ai/v1",
    envKey: "LINKOS_API_KEY",
    website: "https://linkos.ai",
    apiType: "openai-compatible",
    freeTier: "Gateway free trial",
    permanentFree: true,
  },
  {
    id: "baobaogou",
    name: "Baobaogou AI (抱抱狗)",
    baseURL: "https://api.baobaogou.com/v1",
    envKey: "BAOBAOGOU_API_KEY",
    website: "https://baobaogou.com",
    apiType: "openai-compatible",
    freeTier: "Regional trial credits",
    permanentFree: true,
  },

  // ── From provider-search.md: Local / Self-Hosted ───────────────
  {
    id: "aegisgate",
    name: "AegisGate",
    baseURL: "http://localhost:18080/v1",
    website: "https://github.com/ax128/AegisGate",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted security gateway)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "freellmapi",
    name: "FreeLLMAPI",
    baseURL: "http://localhost:3000/v1",
    website: "https://github.com/open-free-llm-api/freellm-hub-data",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted proxy aggregator)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "sglang",
    name: "SGLang Server",
    baseURL: "http://localhost:30000/v1",
    website: "https://github.com/sgl-project/sglang",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted), latency-optimized",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "tabby",
    name: "Tabby AI",
    baseURL: "http://localhost:8080/v1",
    website: "https://github.com/TabbyML/tabby",
    apiType: "openai-compatible",
    freeTier: "Unlimited (self-hosted code completion)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "mindspore",
    name: "MindSpore",
    baseURL: "http://localhost:8080/v1",
    website: "https://github.com/mindspore-ai/mindspore",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local deep learning framework)",
    noCc: true,
    permanentFree: true,
  },
  {
    id: "onnxruntime",
    name: "ONNX Runtime",
    baseURL: "http://localhost:8090/v1",
    website: "https://github.com/microsoft/onnxruntime",
    apiType: "openai-compatible",
    freeTier: "Unlimited (local), multi-platform hardware acceleration",
    noCc: true,
    permanentFree: true,
  },
]

export function getProviders(): Provider[] {
  return PROVIDERS
}

export function getProvider(id: string): Provider | undefined {
  return PROVIDERS.find(p => p.id === id)
}

export function searchProviders(query: string): Provider[] {
  const q = query.toLowerCase()
  return PROVIDERS.filter(p =>
    p.id.toLowerCase().includes(q) ||
    p.name.toLowerCase().includes(q)
  )
}

export interface CuratedFavorite {
  id: string
  tags: string[]
  description: string
}

export const CURATED_FAVORITES: CuratedFavorite[] = [
  { id: "groq", tags: ["coding", "fast", "free", "no-cc"], description: "Fastest free inference, great for code" },
  { id: "cerebras", tags: ["coding", "fast", "free", "no-cc"], description: "World's fastest inference, free tier" },
  { id: "google-gemini", tags: ["coding", "free", "vision", "reasoning", "no-cc"], description: "Gemini 2.5 Flash/Pro, free generous tier" },
  { id: "github-models", tags: ["coding", "free", "no-cc"], description: "Free GPT-4o, Claude, Gemini, DeepSeek" },
  { id: "deepseek", tags: ["coding", "reasoning", "free", "no-cc"], description: "Best open coding model (R1, V3)" },
  { id: "mistral", tags: ["coding", "free", "reasoning"], description: "Codestral + Mistral models, free tier" },
  { id: "cohere", tags: ["coding", "free", "reasoning", "no-cc"], description: "Command R7, free 1M tok/month" },
  { id: "together", tags: ["coding", "free", "fast", "reasoning", "no-cc"], description: "100+ open models, generous free tier" },
  { id: "openrouter", tags: ["coding", "free", "no-cc", "reasoning", "vision"], description: "Gateway to 200+ models, free tier" },
  { id: "sambanova", tags: ["coding", "free", "fast", "no-cc"], description: "Fast free inference, good for code" },
  { id: "fireworks", tags: ["coding", "free", "fast", "no-cc"], description: "Fast free inference, open models" },
  { id: "deepinfra", tags: ["coding", "free", "fast"], description: "Fast free inference, good selection" },
  { id: "hyperbolic", tags: ["coding", "free", "reasoning"], description: "Free tier with reasoning models" },
  { id: "novita", tags: ["coding", "free"], description: "Free tier, 30+ models available" },
  { id: "nebius", tags: ["coding", "free", "fast"], description: "Free tier, fast inference" },
  { id: "perplexity", tags: ["coding", "free", "reasoning"], description: "Sonar models, free 5 RPD" },
  { id: "lepton", tags: ["coding", "free"], description: "Free tier, good model selection" },
  { id: "ai21", tags: ["coding", "free"], description: "Jamba 1.6, free 200 RPM" },
  { id: "arcee", tags: ["coding", "free", "no-cc"], description: "Free, no credit card needed" },
  { id: "huggingface", tags: ["coding", "free", "no-cc", "reasoning", "vision"], description: "100K+ free models via Inference API" },
  { id: "opencode-zen", tags: ["coding", "free", "fast", "no-cc"], description: "OpenCode's built-in free proxy" },
  { id: "grok-xai", tags: ["coding", "free", "reasoning"], description: "Grok-2/3 free with X Premium" },
  { id: "replicate", tags: ["coding", "free", "vision"], description: "Free trial, 100K+ community models" },
  { id: "anyscale", tags: ["coding", "free", "fast"], description: "Serverless endpoint, free credits" },
  { id: "anthropic", tags: ["coding", "reasoning"], description: "Claude 4 Sonnet/Opus, best-in-class coding" },
]

export function getRecommendedProviderIds(): string[] {
  return CURATED_FAVORITES.map(f => f.id)
}

export function getRecommendedProviders(): Provider[] {
  const ids = new Set(getRecommendedProviderIds())
  return PROVIDERS.filter(p => ids.has(p.id))
}

export function getFavoritesByTag(tag: string): Provider[] {
  const ids = new Set(
    CURATED_FAVORITES.filter(f => f.tags.includes(tag)).map(f => f.id),
  )
  return PROVIDERS.filter(p => ids.has(p.id))
}

export function getProviderByEnvKey(envKey: string): Provider | undefined {
  return PROVIDERS.find(p => p.envKey === envKey)
}

export function getFreeProviders(): Provider[] {
  return PROVIDERS.filter(p => p.permanentFree && p.noCc)
}

export function getProvidersSortedByCost(): Provider[] {
  return [...PROVIDERS].sort((a, b) => {
    const aScore = a.permanentFree && a.noCc ? 0 : a.permanentFree ? 1 : a.freeTier ? 2 : 3
    const bScore = b.permanentFree && b.noCc ? 0 : b.permanentFree ? 1 : b.freeTier ? 2 : 3
    return aScore - bScore
  })
}